akka {
  loglevel = INFO #DEBUG

  default-dispatcher {
    fork-join-executor {
      parallelism-min = 2
      parallelism-factor = 1.0
      parallelism-max = 8
    }
  }

  index-dispatcher {
    fork-join-executor {
      parallelism-min = 8
      parallelism-factor = 1.0
      parallelism-max = 16
    }
  }

  jcmd-dispatcher {
    type = Dispatcher
    executor = "thread-pool-executor"
    thread-pool-executor {
      fixed-pool-size = 2
    }
  }
}

http {
  service {
    port = ${?HTTP_PORT}
    port = 8080

    bind-to = ${?HTTP_ADDRESS}
    bind-to = "0.0.0.0"
  }
}
